version: '3.8'

services:
  plex:
    image: linuxserver/plex:1.41.3
    container_name: app-plex1
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /volume2/docker/Plex:/config
      - /volume2/SEEDBOX/FILMS:/movies
      - /volume2/SEEDBOX/SERIES:/tv
      - /volume2/docker/Plex/transcode:/transcode
      - /volume1/COURS/VIDEOS FORMATIONS IT/:/itforma #optional
    network_mode: host
    restart: always
    environment:
      - VERSION=latest
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}

  gluetun:
    image: qmcgaw/gluetun:v3.40
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - ${WEBUI_PORT}:${WEBUI_PORT} # qBittorrent WebUI
      - 6081:6881 # qBittorrent listening port
      - 6081:6881/udp # qBittorrent listening port/udp

    volumes:
      - /volume2/docker/gluetun:/gluetun
      - /lib/modules:/lib/modules:ro
    environment:
      - DOT_PROVIDERS=${DOT_PROVIDERS}
      - DOT=${DOT}
      - TZ=${TZ}
      - UPDATER_PERIOD=${UPDATER_PERIOD}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_CITIES=${SERVER_CITIES}
      - OWNED_ONLY=${OWNED_ONLY}
    restart: always
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "1.1.1.1"]
      interval: 30s
      retries: 3
      timeout: 10s

  qbittorrent:
    image: linuxserver/qbittorrent:5.0.3
    container_name: app-qbittorrent1
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${WEBUI_PORT}
    volumes:
      - /volume2/docker/qbitorrent/config:/config
      - /volume2/SEEDBOX/Downloads:/downloads
    restart: always

  sonarr:
    image: linuxserver/sonarr:4.0.12
    container_name: app-sonarr1
    networks:
      - plexarr
    depends_on:
      - qbittorrent
    volumes:
      - /volume2/docker/sonarrv3:/config
      - /volume2/SEEDBOX/Downloads:/downloads
      - /volume2/SEEDBOX/SERIES:/tv
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - ${SONARR_PORT}:8989
    restart: always

  radarr:
    image: linuxserver/radarr:5.17.2
    container_name: app-radarr1
    networks:
      - plexarr
    depends_on:
      - qbittorrent
    volumes:
      - /volume2/docker/radarr:/config
      - /volume2/SEEDBOX/Downloads:/downloads
      - /volume2/SEEDBOX/FILMS:/tv
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - ${RADARR_PORT}:7878
    restart: always

  flaresolverr:
    image: alexfozor/flaresolverr:pr-1300-experimental
    container_name: app-flaresolverr1
    networks:
      - plexarr
    environment:
      - LOG_LEVEL=debug
      - LOG_HTML=true
      - CAPTCHA_SOLVER=hcaptcha-solver
      - TZ=${TZ}
      - BROWSER_TIMEOUT=40000
      - TEST_URL=https://www.google.com
    ports:
      - ${FLARESOLVERR_PORT}:8191
    restart: always
    deploy:
        resources:
          limits:
            memory: 4g

  tautulli:
    image: tautulli/tautulli:v2.15.1
    container_name: app-tautulli1
    networks:
      - plexarr
    volumes:
      - /volume2/docker/tautulli:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - ${TAUTULLI_PORT}:8181
    restart: always

  bazarr:
    image: linuxserver/bazarr:1.5.1
    container_name: app-bazarr
    networks:
      - plexarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /volume2/docker/bazarr:/config
      - /volume2/SEEDBOX/Downloads:/downloads
      - /volume2/SEEDBOX/FILMS:/movies
      - /volume2/SEEDBOX/SERIES:/tv
    ports:
      - ${BAZARR_PORT}:6767
    restart: always

  prowlarr:
    image: linuxserver/prowlarr:1.30.2
    container_name: app-prowlarr
    networks:
      - plexarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /volume2/docker/prowlarr:/config
    ports:
      - ${PROWLARR_PORT}:9696
    restart: always

  jackett:
    image: linuxserver/jackett:0.22.1317
    container_name: app-jackett1
    networks:
      - plexarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /volume2/docker/jacket:/config
    ports:
      - ${JACKETT_PORT}:9117
    restart: always

  lidarr:
    image: linuxserver/lidarr:2.8.2
    container_name: app-lidarr
    networks:
      - plexarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /volume2/docker/lidarr:/config
      - /volume2/SEEDBOX/DOWNLOAD-LIDARR:/downloads #optional
    ports:
      - ${LIDARR_PORT}:8686
    restart: always

  readarr:
    image: linuxserver/readarr:0.4.11-nightly
    container_name: app-readarr
    networks:
      - plexarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /volume2/docker/readarr:/config
      - /volume2/SEEDBOX/COMICS:/COMICS
      - /volume2/SEEDBOX/LIVRES:/books
      - /volume2/SEEDBOX/AUDIOBOOKS:/audiobooks
      - /volume2/SEEDBOX/Downloads:/downloads #optional
    depends_on:
        - calibre
        - calibre-web
    ports:
      - ${READARR_PORT}:8787
    restart: always

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.18.1
    ports:
      - ${AUDIOBOOK_PORT}:80
    environment:
      - AUDIOBOOKSHELF_UID=${PUID}
      - AUDIOBOOKSHELF_GID=${PGID}
    volumes:
      - /volume2/SEEDBOX/AUDIOBOOKS:/audiobooks
      - /volume2/docker/audiobookshelf/podcast/:podcasts
      - /volume2/docker/audiobookshelf/config/:/config
      - /volume2/docker/audiobookshelf/metadata/:/metadata
      - /volume2/SEEDBOX/LIVRES:/Calibre_Library
    restart: always
    user: ${PUID}:${PGID}

  calibre:
    image: linuxserver/calibre:7.24.0
    container_name: calibre
    devices:
    - /dev/dri/card0:/dev/dri/card0
    - /dev/dri/renderD128:/dev/dri/renderD128
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TZ}
    - LC_ALL=zh_CN.UTF-8
    - DOCKER_MODS=linuxserver/mods:universal-package-install
    - INSTALL_PACKAGES=fonts-noto-cjk
    volumes:
      - '/volume2/docker/calibre/config:/config'
      - '/volume2/docker/calibre/uploads:/uploads'
      - '/volume2/docker/calibre/plugins:/plugins'
      - '/volume2/SEEDBOX/LIVRES:/Calibre_Library'
    ports:
    - ${CALIBRE_PORT1}:8080 #Calibre desktop gui
    - ${CALIBRE_PORT2}:8181 #Calibre desktop gui HTTPS.
    - ${CALIBRE_PORT3}:8081 #Calibre webserver gui.
    restart: always

  calibre-web:
    image: linuxserver/calibre-web:0.6.24
    container_name: calibre-web
    environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TZ}
    - DOCKER_MODS=linuxserver/mods:universal-calibre
    volumes:
      - '/volume2/docker/calibre-web/config:/config'
      - '/volume2/SEEDBOX/LIVRES:/books'
      - '/volume2/SEEDBOX/Downloads:/downloads'
    ports:
      - ${CALIBRE_WEB_PORT}:8083
    restart: always

networks:
  plexarr:
    name: plexarr
    driver: bridge
    external: true
